---
title: "Covid19 vaccine study Fall2021"
author: "Sylvia Rodriguez"
date: "November 3, 2021"
output: 
  html_document:
    toc: true
    toc_depth: 5

---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
TheData <-read.csv(file="fall21.csv",header=TRUE)
TheData <- TheData %>% mutate(across(where(is.character),as.factor))
```

# Introduction

A new  preventative vaccine (covid91) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups consisting of Males, Females, just the drug users, and just those in the LGBTQ community. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Part of the information you need to compute is the so-called effectiveness of the drug for each subgroup of people. Include a 95% confidence interval of the effectiveness for each different subgroup. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

# Males

# Females

# Drug Users

# LGBTQ

# Conclusions and recommendations

